config/routes.rb
Rails.application.routes.draw do
 
 resources :appointment, only: [:new, :create]
 get '/appointment', to: 'appointment#new'
  match '/send_appointment', to: 'appointment#send_appointment', via: 'post'

  resources :pics
  resources :personals
  resources :photos
  get 'donate', to: 'donate#index'

  resources :mail_recipients
  resources :testamonies
  resources :endorsements
  resources :events
  resources :news
  resources :issues
  
  resources :personals do
    post :update_row_order, on: :collection
  end
  
  
  get 'darrell/about', to: 'darrell#about'
  
  get 'darrell/personalreferences', to: 'darrell#personalreferences'
  get 'darrell/issues', to: 'darrell#issues'
  get 'darrell/video', to: 'darrell#video'
  
  resources :contact, only: [:new, :create]
  get '/contact', to: 'contact#new'
  resources :support, only: [:new, :create]
  get '/support', to: 'support#new'
 
 
   match '/send_mail', to: 'contact#send_mail', via: 'post'
   match '/send_support_mail', to: 'support#send_support_mail', via: 'post'
   

  get 'bio', to: 'bio#index'

  get 'admin', to: 'admin#index'

  resources :pages
 
  get 'welcome/index'

   root 'welcome#index'
   
      get '/signup' => 'users#new'
      post '/users' => 'users#create'
      get 'users', to: 'users#index'
      
      
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
        
        

end

app/models/appointment.rb
class Appointment 
  
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :organization, :cellphone, :email, :email_confirmation, :topic, :purpose, :speaking, :speech_topic, :speech_duration, :qa, :qa_duration, :time_requested, :time_requested_other, :date, :time, :location, :address, :attendees_number, :notable_attendees, :press, :background_info, :website

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :cellphone, presence: true
  validates :speaking, presence: true
  validates :email, presence: true
  validates :email_confirmation, presence: true
    validates_confirmation_of :email, :message => "should match email"
    validates :date, presence: true
   
  
end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :name, :email, :body

  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  
  validates :firstname, presence: true, unless: "organization?"
  validates :lastname, presence: true, unless: "organization?"
  
  default_scope  {order 'rank ASC', 'lastname ASC', 'organization ASC'}
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_attached_file :avatar, styles: { medium: "900x900>", thumb: "100x100" }, default_url: "issues/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
     default_scope  {order 'start_time ASC'}
     
     
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x473#", thumb: "300x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/mail_recipient.rb
class MailRecipient < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x400#", thumb: "150x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
   default_scope  {order 'published_at DESC'}
  
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
  include RankedModel
    ranks :row_order
    
  has_attached_file :avatar, styles: { medium: "400x400", thumb: "150x100#" }, default_url: "personals/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
   validates :name, presence: true
   validates :description, presence: true
   validates :content, presence: true
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  
  has_attached_file :avatar, styles: { medium: "680x400", thumb: "150x100" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 6.megabytes
  
  
   default_scope  {order 'created_at DESC'}
   
   
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "900x700", thumb: "150x150#" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 2.megabytes
  
  
  
end

app/models/support.rb
class Support
  
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :address, :comments, :help
  validates :name, presence: true
  validates :email, presence: true
end

app/models/testamony.rb
class Testamony < ActiveRecord::Base
  
  validates :name, presence: true
  validates :quote, presence: true
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

before_filter :authorize, except: [:show]
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issues = Issue.all 
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :content, :avatar)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/issues/_form.html.erb
<%= bootstrap_form_for(@issue, :html => { :multipart => true }) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   
    <%= f.text_field :title %>
  </div>
  <div class="field">
	  
	  <% unless @issue.avatar.blank? %>
	  <p><b>Current image</b><br/><%= link_to (image_tag @issue.avatar.url(:thumb)), @issue.avatar.url(:original), target: '_blank' %> </p><%= f.file_field :avatar, label: 'Add a new image', class: 'choose-image'%></p>
	  <% else %>
	  <div class="field">
	  <%= f.file_field :avatar, label: 'Add an image for this issue - ', class: 'choose-image'%>
  </div>
	  <% end %>
   
    <%= f.text_area :description, maxlength: "150", id: "alloptions" %>
  </div>
  <div class="field">
    
    <%= f.text_area :content, class: 'edit-content' %>
  </div>
  <div class="actions pull-right">
    <%= f.submit %>
  </div>
<% end %>

<script>
$(document).ready(function(){
$('textarea#alloptions').maxlength({
alwaysShow: true,
threshold: 10,
	showCharsTyped: false,
warningClass: "label label-success",
limitReachedClass: "label label-important label-danger",
separator: ' of ',
preText: 'You have ',
postText: ' characters remaining.'
});
});
</script>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<div class="clear"></div>
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Issues Editor</h1>

<div class="caveat">
	
	<strong>WARNING</strong> - Only edit these pages if you know what you are doing. You can not undo any changes!
	
</div>
	
	
<table class="table table-hover">
    <% @issues.each do |issue| %>
      <tr>
		<td> <span class="label label-warning"><%= issue.id %></span> <td class="page-title-col"><%= issue.title %></td>
        
      <td><%= link_to 'Edit', edit_issue_path(issue) %> | <%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
	 
    <% end %>
 
</table>
<br>

<br>

<% content_for :rh do %>
<div class="card admin-card">
<div class="card-block">
	
<p class="card-text"><%= link_to 'Add a New Issue', new_issue_path, class: "btn btn-primary" %></p>
<p class="card-text"><%= link_to 'Go to Issues page', '/darrell/issues', class: "btn btn-primary" %></p>
</div>
</div>
<% end %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<div class="clear"></div>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
	<% if current_user %>
    	<div class="edit alert" >
    <i> <%= link_to ' Edit ', edit_issue_path(@issue), class: "admin-edit fa fa-edit", dismissible: true %> </i>|<i> <%= link_to ' Delete', @issue, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin-edit fa fa-trash" %></i>
 
    <button class="close" data-dismiss="alert" type="button">
        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
      </button>
   
    </div>
<% end %>

<h1 class="issue-title"> <%=  @issue.title %></h1>
 <% if @issue.avatar.blank? %>
 
	
	
 <% else %>
<div class="news-img">
 <%= image_tag @issue.avatar.url(:medium), class:"img-fluid"%>
</div>
 <% end%>
 

 
 



<p>
 
  <%= simple_format(@issue.content) %>
</p>

 


	

<div class="clear"></div>

	


 

	

<div class="clear"></div>

<%= content_for :rh do %>

<% if current_user %><div class="edit alert" >
 <i> <%= link_to ' Add a new Issue  ', new_issue_path, class: "admin-edit fa fa-plus", dismissible: true %> </i>
 
 <button class="close" data-dismiss="alert" type="button">
     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
   </button>
   
 </div>
 <% end %>
 
 
<% @issues.each do |i| %>
 <% unless i == @issue %>
<div class="card">
	
	
		<%= image_tag i.avatar.url(:medium), class: "img-fluid"%>
		<div class="card-block">
<h5 class="card-title"><%= link_to i.title, i %></h5>
<p><%= i.description %></p>
 <p><%= link_to 'Learn more', i, class: "btn btn-primary" %></p>
</div>


</div>
<% end %>
<% end %>
<% end %>
<%= link_to 'All issues', '/darrell/issues' %>