config/routes.rb
Rails.application.routes.draw do
 
 resources :appointment, only: [:new, :create]
 get '/appointment', to: 'appointment#new'
  match '/send_appointment', to: 'appointment#send_appointment', via: 'post'

  resources :pics
  resources :personals
  resources :photos
  get 'donate', to: 'donate#index'

  resources :mail_recipients
  resources :testamonies
  resources :endorsements
  resources :events
  resources :news
  resources :issues
  
  resources :personals do
    post :update_row_order, on: :collection
  end
  
  
  get 'darrell/about', to: 'darrell#about'
  
  get 'darrell/personalreferences', to: 'darrell#personalreferences'
  get 'darrell/issues', to: 'darrell#issues'
  get 'darrell/video', to: 'darrell#video'
  
  resources :contact, only: [:new, :create]
  get '/contact', to: 'contact#new'
  resources :support, only: [:new, :create]
  get '/support', to: 'support#new'
 
 
   match '/send_mail', to: 'contact#send_mail', via: 'post'
   match '/send_support_mail', to: 'support#send_support_mail', via: 'post'
   

  get 'bio', to: 'bio#index'

  get 'admin', to: 'admin#index'

  resources :pages
 
  get 'welcome/index'

   root 'welcome#index'
   
      get '/signup' => 'users#new'
      post '/users' => 'users#create'
      get 'users', to: 'users#index'
      
      
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
        
        

end

app/models/appointment.rb
class Appointment 
  
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :organization, :cellphone, :email, :email_confirmation, :topic, :purpose, :speaking, :speech_topic, :speech_duration, :qa, :qa_duration, :time_requested, :time_requested_other, :date, :time, :location, :address, :attendees_number, :notable_attendees, :press, :background_info, :website

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :cellphone, presence: true
  validates :speaking, presence: true
  validates :email, presence: true
  validates :email_confirmation, presence: true
    validates_confirmation_of :email, :message => "should match email"
    validates :date, presence: true
   
  
end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :name, :email, :body

  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  
  validates :firstname, presence: true, unless: "organization?"
  validates :lastname, presence: true, unless: "organization?"
  
  default_scope  {order 'rank ASC', 'lastname ASC', 'organization ASC'}
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_attached_file :avatar, styles: { medium: "900x900>", thumb: "100x100" }, default_url: "issues/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
     default_scope  {order 'start_time ASC'}
     
     
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x473#", thumb: "300x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x400#", thumb: "150x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
   default_scope  {order 'published_at DESC'}
  
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
  include RankedModel
    ranks :row_order
    
  has_attached_file :avatar, styles: { medium: "400x400", thumb: "150x100#" }, default_url: "personals/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
   validates :name, presence: true
   validates :description, presence: true
   validates :content, presence: true
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  
  has_attached_file :avatar, styles: { medium: "680x400", thumb: "150x100" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 6.megabytes
  
  
   default_scope  {order 'created_at DESC'}
   
   
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "900x700", thumb: "150x150#" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 2.megabytes
  
  
  
end

app/models/support.rb
class Support
  
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :address, :comments, :help
  validates :name, presence: true
  validates :email, presence: true
end

app/models/testamony.rb
class Testamony < ActiveRecord::Base
  
  validates :name, presence: true
  validates :quote, presence: true
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/admin/index.html.erb
<h1>Admin Center</h1>
<p class="lead">This is the Admin hub from where you can manage the website. Only registered admins can see this area.</p>
<h3>Admin Users</h3>
<p>The following are registered Admin users for the website. Contact Rob if you need to add (or change the details/permissions of) administrators.</p>
	<p>
	<% @admin.each do |a|%>
	
	<strong><%= a.name.capitalize %></strong> - <%= mail_to a.email %><br/>
	
	<% end %>
<div class="admin-panel">	
<h3>Events</h3>
<p>Add and manage Events here. Just head to the Event page to add a new one, or go to a specific event to edit it.</p>

<p><%= link_to 'Manage Events', events_path, class: "btn btn-primary" %> 
</div>


<div class="admin-panel">	
<h3>Issues</h3>
<p>Add and manage the hot button topics here. Add an image, a leader, and  content for each, and build out the panels in the Issues section. Currently hidden from public viewing.</p>

<p><%= link_to 'Manage Issues', issues_path, class: "btn btn-primary" %> 
</div>
<div class="admin-panel">	
<h3>News</h3>
<p>Got news?</p>
<p><%= link_to 'Add a Story', new_news_path, class: "btn btn-primary" %>
</div>
	
<div class="admin-panel">	
<h3>Endorsement</h3>
<p>Add and manage the endorsements here.</p>
<p><%= link_to 'Add a Story', new_news_path, class: "btn btn-primary" %>
</div>
		
		
	<div class="admin-panel">
<h3>Upload Hi Q Media</h3>
<p>Use this section to add hi quality images of Darrell for use by outside agencies, new, IEs etc.. Max file size is 6MB, so make sure the file conforms to this limit. Use Photoshop, etc to reduce the filesize if needed.</p> 
<p><%= link_to 'Manage Media Hi-Q images', photos_path, class: "btn btn-primary" %>
</div>
<div class="admin-panel">	
	
<h3>Testimonies</h3>
<p>The sliding quotes are managed here. </p>

<p><%= link_to 'Manage Testamonies', testamonies_path, class: "btn btn-primary" %> 
</div>
<div class="admin-panel">	
<h3>Personal References</h3>
<p>The little stories of support can be added here. Supports an image, but not required.</p>
	
<p><%= link_to 'Manage Personal References', darrell_personalreferences_path, class: "btn btn-primary" %> 

</div>
<div class="admin-panel">
<h3>Mailer Recipients</h3>
<p>Control who receives the messages from the Support form (temporary) and the website Contact form</p>
<p><%= link_to 'Manage Mailer Recipients', mail_recipients_path, class: "btn btn-primary" %> 

</div>
<div class="admin-panel">
<h3>Pages</h3>
<p>The content on the welcome page and the About Darrell page is editable by admin. Use this section to make changes. Adding pages will have no effect, and changing the page ttle could cause problems. Only use this section if you know what you are doing!</p>
<p><%= link_to 'Manage Pages', pages_path, class: "btn btn-primary" %> 
</div>