config/routes.rb
Rails.application.routes.draw do
 
 resources :appointment, only: [:new, :create]
 get '/appointment', to: 'appointment#new'
  match '/send_appointment', to: 'appointment#send_appointment', via: 'post'

  resources :pics
  resources :personals
  resources :photos
  get 'donate', to: 'donate#index'

  resources :mail_recipients
  resources :testamonies
  resources :endorsements
  resources :events
  resources :news
  resources :issues
  
  resources :personals do
    post :update_row_order, on: :collection
  end
  
  
  get 'darrell/about', to: 'darrell#about'
  
  get 'darrell/personalreferences', to: 'darrell#personalreferences'
  get 'darrell/issues', to: 'darrell#issues'
  get 'darrell/video', to: 'darrell#video'
  
  resources :contact, only: [:new, :create]
  get '/contact', to: 'contact#new'
  resources :support, only: [:new, :create]
  get '/support', to: 'support#new'
 
 
   match '/send_mail', to: 'contact#send_mail', via: 'post'
   match '/send_support_mail', to: 'support#send_support_mail', via: 'post'
   

  get 'bio', to: 'bio#index'

  get 'admin', to: 'admin#index'

  resources :pages
 
  get 'welcome/index'

   root 'welcome#index'
   
      get '/signup' => 'users#new'
      post '/users' => 'users#create'
      get 'users', to: 'users#index'
      
      
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
        
        

end

app/models/appointment.rb
class Appointment 
  
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :organization, :cellphone, :email, :email_confirmation, :topic, :purpose, :speaking, :speech_topic, :speech_duration, :qa, :qa_duration, :time_requested, :time_requested_other, :date, :time, :location, :address, :attendees_number, :notable_attendees, :press, :background_info, :website

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :cellphone, presence: true
  validates :speaking, presence: true
  validates :email, presence: true
  validates :email_confirmation, presence: true
    validates_confirmation_of :email, :message => "should match email"
    validates :date, presence: true
   
  
end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :name, :email, :body

  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  
  validates :firstname, presence: true, unless: "organization?"
  validates :lastname, presence: true, unless: "organization?"
  
  default_scope  {order 'rank ASC', 'lastname ASC', 'organization ASC'}
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_attached_file :avatar, styles: { medium: "900x900>", thumb: "100x100" }, default_url: "issues/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
     default_scope  {order 'start_time ASC'}
     
     
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x473#", thumb: "300x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/mail_recipient.rb
class MailRecipient < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x400#", thumb: "150x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
   default_scope  {order 'published_at DESC'}
  
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
  include RankedModel
    ranks :row_order
    
  has_attached_file :avatar, styles: { medium: "400x400", thumb: "150x100#" }, default_url: "personals/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
   validates :name, presence: true
   validates :description, presence: true
   validates :content, presence: true
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  
  has_attached_file :avatar, styles: { medium: "680x400", thumb: "150x100" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 6.megabytes
  
  
   default_scope  {order 'created_at DESC'}
   
   
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "900x700", thumb: "150x150#" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 2.megabytes
  
  
  
end

app/models/support.rb
class Support
  
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :address, :comments, :help
  validates :name, presence: true
  validates :email, presence: true
end

app/models/testamony.rb
class Testamony < ActiveRecord::Base
  
  validates :name, presence: true
  validates :quote, presence: true
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page], :per_page => 10)
    @title = "News"
  end

  # GET /news/1
  # GET /news/1.json
  def show
    
    @stories = News.first(8)
    @title = @news.title
    @description = @news.description
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description, :content, :avatar, :published_at)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/news/_form.html.erb
<%= bootstrap_form_for(@news) do |f| %>
  
  <div class="field">
   
    <%= f.text_field :title %>
	
	<%= f.datetime_select :published_at %>
	
  	  <% unless @news.avatar.blank? %>
  	  <p><b>Current image</b><br/><%= link_to (image_tag @news.avatar.url(:thumb)), @news.avatar.url(:original), target: '_blank' %> </p><%= f.file_field :avatar, label: 'Add a new image', class: 'choose-image'%></p>
  	  <% else %>
  	  <div class="field">
  	  <%= f.file_field :avatar, label: 'Add an image for this story - ', class: 'choose-image'%>
    </div>
  	  <% end %>
	  
  </div>
  <div class="field">
  
    <%= f.text_area :description, maxlength: "130", id: "alloptions"%>
  </div>
  <div class="field">
   
    <%= f.text_area :content, class: "edit-content", id: "summernote"%>
  </div>
   <div class="actions pull-right">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
$('#summernote').summernote({
	
  toolbar: [
    // [groupName, [list of button]]
	  ['insert', ['link']],
	  ['image', ['none']],
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['para', ['style', 'ul', 'ol']]
  ]
});
</script>

<script>
$(document).ready(function(){
$('textarea#alloptions').maxlength({
alwaysShow: true,
threshold: 10,
	showCharsTyped: false,
warningClass: "label label-success",
limitReachedClass: "label label-important label-danger",
separator: ' of ',
preText: 'You have ',
postText: ' characters remaining.'
});
});
</script>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<%= content_for :jumbotron do %>
<div  class="outerwrapper-news">
    <!-- Main jumbotron for a primary marketing message or call to action -->
  
   
		   <div class="jumbotron" >
      
        <div class="lead jumbylead">
			  <div class="container "><div class="jumboleader">Latest News</div></div>
        
      </div>
    </div>

</div>


<% end %>




    <% @news.each do |news| %>
 <div class="row news-index">
     <div class="col-md-3 news-img"> <%= image_tag news.avatar.url(:thumb)%>  </div> 
      <div class="col-md-9 news-teaser"><h3>  <%= link_to news.title, news %> </h3>
		 <small class="text-muted"><% unless news.published_at.blank? %><%= news.published_at.strftime("%B %d %Y")%><% end %></small> 
    <p><%= news.description %> <small><%=     
    link_to "read more", news 
 %></small><br/>
</p>
 
      </div>
		
		
		  </div>
		  
		 
		  
		  
    <% end %>
	<div class="pagination">
  <%= will_paginate @news %>
</div>
<br>

<% content_for :rh do %>
<% if current_user %><div class="edit alert" >
 <i> <%= link_to ' Add a new story  ', new_news_path, class: "admin-edit fa fa-plus", dismissible: true %> </i>
 
 <button class="close" data-dismiss="alert" type="button">
     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
   </button>
   
 </div>
 <% end %>
 
 <%= render '/layouts/endorsement_panel.html.erb' %>
 <%= render '/layouts/support_panel.html.erb' %>
 
 
<% end %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
 	<% if current_user %>
 	<div class="edit alert" >
 <i> <%= link_to ' Edit ', edit_news_path(@news), class: "admin-edit fa fa-edit", dismissible: true %> </i>|<i> <%= link_to ' Delete', @news, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin-edit fa fa-trash" %></i>
 
 <button class="close" data-dismiss="alert" type="button">
     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
   </button>
   
 </div>
<% end %>
 <% if @news.avatar.blank? %>
 
	
	
 <% else %>
<div class="news-img">
 <%= image_tag @news.avatar.url(:medium), class:"img-fluid"%>
</div>
 <% end%>
 
<h1> <%= @news.title %></h1>
 
 <h6 class="text-muted"><%= @news.published_at.strftime("%B %d %Y")%></h6> 

<p class="lead">

  <%= @news.description %>


<p>
 
  <%= simple_format(@news.content) %>
</p>

 


	

<div class="clear"></div>

<%= content_for :rh do %>

<% if current_user %><div class="edit alert" >
 <i> <%= link_to ' Add a new story  ', new_news_path, class: "admin-edit fa fa-plus", dismissible: true %> </i>
 
 <button class="close" data-dismiss="alert" type="button">
     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
   </button>
   
 </div>
 <% end %>
 

<% @stories.each do |i| %>

 <% unless i == @news %>

	 <div class="news-card">
	<% unless i.avatar.blank? %>
		<%= image_tag i.avatar.url(:thumb), class: "img-fluid"%><% end %>

<h5><%= link_to i.title, i %></h5>
<h6 class="text-muted"><% unless i.published_at.blank? %><%= i.published_at.strftime("%B %d %Y")%><% end %></h6> 
 </div>
<% end %>
<% end %><% end %>