config/routes.rb
Rails.application.routes.draw do
 
 resources :appointment, only: [:new, :create]
 get '/appointment', to: 'appointment#new'
  match '/send_appointment', to: 'appointment#send_appointment', via: 'post'

  resources :pics
  resources :personals
  resources :photos
  get 'donate', to: 'donate#index'

  resources :mail_recipients
  resources :testamonies
  resources :endorsements
  resources :events
  resources :news
  resources :issues
  
  resources :personals do
    post :update_row_order, on: :collection
  end
  
  
  get 'darrell/about', to: 'darrell#about'
  
  get 'darrell/personalreferences', to: 'darrell#personalreferences'
  get 'darrell/issues', to: 'darrell#issues'
  get 'darrell/video', to: 'darrell#video'
  
  resources :contact, only: [:new, :create]
  get '/contact', to: 'contact#new'
  resources :support, only: [:new, :create]
  get '/support', to: 'support#new'
 
 
   match '/send_mail', to: 'contact#send_mail', via: 'post'
   match '/send_support_mail', to: 'support#send_support_mail', via: 'post'
   

  get 'bio', to: 'bio#index'

  get 'admin', to: 'admin#index'

  resources :pages
 
  get 'welcome/index'

   root 'welcome#index'
   
      get '/signup' => 'users#new'
      post '/users' => 'users#create'
      get 'users', to: 'users#index'
      
      
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
        
        

end

app/models/appointment.rb
class Appointment 
  
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :organization, :cellphone, :email, :email_confirmation, :topic, :purpose, :speaking, :speech_topic, :speech_duration, :qa, :qa_duration, :time_requested, :time_requested_other, :date, :time, :location, :address, :attendees_number, :notable_attendees, :press, :background_info, :website

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :cellphone, presence: true
  validates :speaking, presence: true
  validates :email, presence: true
  validates :email_confirmation, presence: true
    validates_confirmation_of :email, :message => "should match email"
    validates :date, presence: true
   
  
end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :name, :email, :body

  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  
  validates :firstname, presence: true, unless: "organization?"
  validates :lastname, presence: true, unless: "organization?"
  
  default_scope  {order 'rank ASC', 'lastname ASC', 'organization ASC'}
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_attached_file :avatar, styles: { medium: "900x900>", thumb: "100x100" }, default_url: "issues/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
     default_scope  {order 'start_time ASC'}
     
     
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x473#", thumb: "300x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/news.rb
class News < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "710x400#", thumb: "150x100#" }, default_url: "news/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
   default_scope  {order 'published_at DESC'}
  
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
  include RankedModel
    ranks :row_order
    
  has_attached_file :avatar, styles: { medium: "400x400", thumb: "150x100#" }, default_url: "personals/:styles/missing.jpg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
   validates :name, presence: true
   validates :description, presence: true
   validates :content, presence: true
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  
  has_attached_file :avatar, styles: { medium: "680x400", thumb: "150x100" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 6.megabytes
  
  
   default_scope  {order 'created_at DESC'}
   
   
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "900x700", thumb: "150x150#" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, presence: true
   
   validates_attachment_size :avatar, :less_than => 2.megabytes
  
  
  
end

app/models/support.rb
class Support
  
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :address, :comments, :help
  validates :name, presence: true
  validates :email, presence: true
end

app/models/testamony.rb
class Testamony < ActiveRecord::Base
  
  validates :name, presence: true
  validates :quote, presence: true
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]
before_filter :authorize, except: [:index]
  # GET /endorsements
  # GET /endorsements.json
  def index
    @testamonies = Testamony.all
    @first = Testamony.first
    @endorsements = Endorsement.all
    @sacelecteds = Endorsement.where(category: 'Sac Elected') 
    @regelecteds = Endorsement.where(category: 'Regional Elected')
    @stateelecteds = Endorsement.where(category: 'State Elected')
    @formerelecteds = Endorsement.where(category: 'Former Elected')
    @orgs = Endorsement.where(category: 'Organization')
    @individuals = Endorsement.where(category: 'Community Leader')
    
    @title = "Endorsements for Darrell"
    @description = "Endorsements for Darrell Steinberg for Sacramento Mayor 2016"
  end

  # GET /endorsements/1
  # GET /endorsements/1.json
  def show
  end

  # GET /endorsements/new
  def new
    @endorsement = Endorsement.new
  end

  # GET /endorsements/1/edit
  def edit
  end

  # POST /endorsements
  # POST /endorsements.json
  def create
    @endorsement = Endorsement.new(endorsement_params)

    respond_to do |format|
      if @endorsement.save
        format.html { redirect_to endorsements_path, notice: 'Endorsement was successfully created.' }
        format.json { render :show, status: :created, location: @endorsement }
      else
        format.html { render :new }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endorsements/1
  # PATCH/PUT /endorsements/1.json
  def update
    respond_to do |format|
      if @endorsement.update(endorsement_params)
        format.html { redirect_to endorsements_path, notice: 'Endorsement was successfully updated.' }
        format.json { render :show, status: :ok, location: @endorsement }
      else
        format.html { render :edit }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endorsements/1
  # DELETE /endorsements/1.json
  def destroy
    @endorsement.destroy
    respond_to do |format|
      format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endorsement_params
      params.require(:endorsement).permit(:firstname, :lastname, :category, :title, :organization, :rank)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/endorsements/_form.html.erb
<%= bootstrap_form_for(@endorsement, label_errors: true, :html => { :class => "form-horizontal" }) do |f| %>
 
  <div class="field">
   
    <%= f.text_field :firstname, placeholder: "Firstname"%>
  </div>
  <div class="field">
   
    <%= f.text_field :lastname, placeholder: "Lastname"%>
  </div>
  <div class="field">
    
   
	<%= f.select :category, ['Organization', 'Sac Elected', 'Regional Elected','State Elected', 'Former Elected','Community Leader'] %>
  </div>
  <div class="field">
   
    <%= f.text_field :title, placeholder: "Title (optional)"%>
  </div>
  <div class="field">
   
    <%= f.text_field :organization, placeholder: "Organization (optional - unless this entry is for an Organization)"%>
  </div>
  <div class="field">
   
    <%= f.number_field :rank ,placeholder: "Position for elected officals only. 0 is highest."%>
  </div>
  <div class="actions pull-right">
    <%= f.submit %>
  </div>
<% end %>

app/views/endorsements/edit.html.erb
<h1>Editing Endorsement</h1>

<%= render 'form' %>


<%= link_to 'Back', endorsements_path %>


<%= content_for :rh do %>

<%= render '/layouts/endorsement_help.html.erb'%>

<% end %>

app/views/endorsements/index.html.erb
<%= content_for :override do %>


<div class="testamonies">

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
	 
	  <% @testamonies.each_with_index do |t,i| %>
    <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="discy <% if t == @first %>active<% end %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner" role="listbox">
	   <% @testamonies.each do |testamony| %>
	   
    <div class="carousel-item <% if testamony == @first %>active<% end %>">
		<div class="testamony-quote">
      <i><span class="fa fa-quote-left quote"></span> </i> <%= testamony.quote %> <i><span class="fa fa-quote-right quote"></span> </i>
	  
  </div>
  
 <div class="testamony-name"><%= testamony.name %></div>
 
 <div class="testamony-title"><%= testamony.title %></div>
 
	    </div>
	  <% end %>
  
	
	
</div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  
  </div>
  
</div>

<% end %>
	
	
	
	<h1>Endorsements for Darrell</h1>
	
	<p class="lead">Join the growing group of Darrell supporters</p>
	
<% unless @orgs.blank? %>
<h2>Organizations</h2> <% end %>
	<% @orgs.each do |e| %>
	<p><%= e.organization %>  <% if current_user %> <span class="label label-warning"> <%= e.rank %></span>   <span class="edit alert edit-endorsement" >
	   <%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %></p>
</span>
<% end %></p>
<% end %>
	

<h2>Sacramento Elected Officials</h2> 
  
<% @sacelecteds.each do |e| %>
  
 <p><strong><%= e.firstname %> <%= e.lastname %></strong>  <%= e.title %> <% if current_user %> 
	<span class="label label-warning"> <%= e.rank %></span>
	  <span class="edit alert edit-endorsement" >
		   <%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %><% end %> </p>
  </span>
<% end %>
		 
<h2>Regional Elected Officials</h2> 

<% @regelecteds.each do |e| %>
<p><strong><%= e.firstname %> <%= e.lastname %></strong>  <%= e.title %> <% if current_user %> 
<span class="label label-warning"> <%= e.rank %></span>
<span class="edit alert edit-endorsement" >
<%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %><% end %> </p>
</span>
<% end %>		 
		 
<h2>State Elected Officials</h2> 

<% @stateelecteds.each do |e| %>
<p> <%= e.title %> <strong><%= e.firstname %> <%= e.lastname %></strong> <% if current_user %> 
<span class="label label-warning"> <%= e.rank %></span>
<span class="edit alert edit-endorsement" >
<%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %><% end %> </p>
</span>
<% end %>	



<h2>Former Elected Officials</h2> 

<% @formerelecteds.each do |e| %>
<p> <strong><%= e.firstname %> <%= e.lastname %></strong> <%= e.title %> <% if current_user %> 
<span class="label label-warning"> <%= e.rank %></span>
<span class="edit alert edit-endorsement" >
<%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %><% end %> </p>
</span>
<% end %>	


	 
		 
<h2>Community Endorsements</h2> 

<% @individuals.each do |e| %>

<p><strong><%= e.firstname %> <%= e.lastname %></strong>   <%= e.title %>  <% if current_user %>   <span class="edit alert edit-endorsement" >
<%= link_to ' edit', edit_endorsement_path(e), class: "admin-edit fa fa-edit" %> |  <%= link_to ' delete', endorsement_path(e), class: "admin-edit fa fa-trash", :method => :delete, data: { confirm: ('messages.confirm_delete'), ok: ('buttons.ok'), cancel: ('buttons.cancel')} %><% end %> </p>
</span></p></span>


		
	<% end %>	
		
	
		
		<p>	<a href="#" class="crunchify-top">↑Back to top</a>
		
		
		<%= content_for :rh do %>
		
		<% if current_user %><div class="edit alert" >
		 <i> <%= link_to ' Add an endorsement  ', new_endorsement_path, class: "admin-edit fa fa-user-plus", dismissible: true %> </i>
 
		 <button class="close" data-dismiss="alert" type="button">
		     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
		   </button>
   
		 </div>
		 
		 <div class="edit alert" >
		 		 <i> <%= link_to ' Add a testamony  ', new_testamony_path, class: "admin-edit fa fa-user-plus", dismissible: true %> </i>
 
		 		 <button class="close" data-dismiss="alert" type="button">
		 		     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
		 		   </button>
   
		 		 </div>
				 
				 <% else %>
				 
				
		 <% end %>
		<%= render '/layouts/endorsement_panel.html.erb' %>
		
		<%= render '/layouts/support_panel.html.erb' %>
		
		<% end %>
		
		
		
		
		<script>
		$('.carousel').carousel({
		   interval: 6000
		   })
		   
		  
		</script>
		   
		   
		   <script>            
		   	jQuery(document).ready(function() {
		   		var offset = 220;
		   		var duration = 500;
		   		jQuery(window).scroll(function() {
		   			if (jQuery(this).scrollTop() > offset) {
		   				jQuery('.crunchify-top').fadeIn(duration);
		   			} else {
		   				jQuery('.crunchify-top').fadeOut(duration);
		   			}
		   		});
 
		   		jQuery('.crunchify-top').click(function(event) {
		   			event.preventDefault();
		   			jQuery('html, body').animate({scrollTop: 0}, duration);
		   			return false;
		   		})
		   	});
		   </script>
		   

app/views/endorsements/new.html.erb
<h1>New Endorsement</h1>

<%= render 'form' %>

<%= link_to 'Back', endorsements_path %>

<%= content_for :rh do %>

<%= render '/layouts/endorsement_help.html.erb'%>

<% end %>

app/views/endorsements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @endorsement.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @endorsement.lastname %>
</p>

<p>
  <strong>Category:</strong>
  <%= @endorsement.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @endorsement.title %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @endorsement.organization %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @endorsement.rank %>
</p>

<%= link_to 'Edit', edit_endorsement_path(@endorsement) %> |
<%= link_to 'Back', endorsements_path %>